id: I6D9A4AD0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T21:59:32+00:00'
last_modified: '2022-06-10T05:08:27.038116+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC308
  title: 'ཨེ་ཝཾ་བཀའ་འབུམ་ཁ་སྐོང་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E804:
      image_group_id: I4PD3945
      title: Volume 1 of e waM bka' 'bum kha skong /
      total_pages: 446
      order: 1
      base_file: E804.txt
    B519:
      image_group_id: I4PD3946
      title: Volume 2 of e waM bka' 'bum kha skong /
      total_pages: 446
      order: 2
      base_file: B519.txt
    0967:
      image_group_id: I4PD3947
      title: Volume 3 of e waM bka' 'bum kha skong /
      total_pages: 414
      order: 3
      base_file: 0967.txt
    A385:
      image_group_id: I4PD3948
      title: Volume 4 of e waM bka' 'bum kha skong /
      total_pages: 438
      order: 4
      base_file: A385.txt
    62AF:
      image_group_id: I4PD3949
      title: Volume 5 of e waM bka' 'bum kha skong /
      total_pages: 450
      order: 5
      base_file: 62AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
